- name: "🛠️ Apply Docker user config"
  tags: [docker, config]
  block:
    - name: "📂 Ensure Docker config directory exists"
      ansible.builtin.file:
        path: /root/.docker/
        state: directory
        owner: root
        group: root
        mode: "0700"

    - name: "📄 Deploy Docker config file"
      ansible.builtin.copy:
        src: secrets/docker_config/{{ inventory_hostname }}/config.json
        dest: /root/.docker/config.json
        owner: root
        group: root
        mode: "0600"
        force: false
