- name: 🧰 Install System Packages
  tags: [packages]
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - python3-docker
    state: present
    update_cache: true

- name: 📦 Apply Docker Daemon Config
  tags: [docker, config]
  when: common_docker_daemon_config is defined
  block:
    - name: 📁 Create Docker Config Directory
      tags: [docker, config]
      ansible.builtin.file:
        path: /etc/docker
        state: directory
        mode: "0755"

    - name: 📄 Write Docker Daemon Config
      tags: [docker, config]
      ansible.builtin.copy:
        dest: /etc/docker/daemon.json
        content: "{{ common_docker_daemon_config | to_nice_json }}"
        owner: root
        group: root
        mode: "0600"

- name: 🏗️ Add Docker Repository
  tags: [docker, packages]
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: https://download.docker.com/linux/ubuntu
    suites: '{{ ansible_facts["distribution_release"] }}'
    components: [stable]
    signed_by: https://download.docker.com/linux/ubuntu/gpg
    state: present
    enabled: true

- name: 🐳 Install Docker Engine
  tags: [docker, packages]
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: 👤 Add User to Docker Group
  tags: [docker, user]
  ansible.builtin.user:
    name: '{{ ansible_facts["user_id"] }}'
    groups: ["docker"]
    append: true
