---
- name: Copy docker daemon configuration
  ansible.builtin.copy:
    src: files/docker/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0600'

- name: Restart docker service
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Cron job - update services
  ansible.builtin.cron:
    name: 'update services'
    minute: '0'
    hour: '0'
    day: '1'
    job: 'cd /home/woody/solero-server-deployment && /usr/bin/docker compose down && /usr/bin/docker compose pull && /usr/bin/docker compose up -d'

- name: Cron job - update discourse
  ansible.builtin.cron:
    name: 'update discourse'
    minute: '30'
    hour: '0'
    day: '1'
    job: 'cd /var/discourse && ./launcher rebuild app'

- name: Create docker network
  community.docker.docker_network:
    name: solero

- name: Add 'rc' alias 
  ansible.builtin.lineinfile:
    dest: /etc/cloud/templates/hosts.debian.tmpl
    line: "{{ hostvars['rc'].ansible_host }} rc"
    state: present

- name: Add 'jessie' alias 
  ansible.builtin.lineinfile:
    dest: /etc/cloud/templates/hosts.debian.tmpl
    line: "{{ hostvars['jessie'].ansible_host }} jessie"
    state: present

- name: Configure journald
  community.general.ini_file:
    path: /etc/systemd/journald.conf
    section: Journal
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - option: Storage
      value: volatile
    - option: Compress
      value: 'yes'
    - option: SystemMaxUse
      value: 50M
    - option: SystemMaxFileSize
      value: 5M
    - option: ForwardToSyslog
      value: 'no'

- name: Restart systemd-journald service
  ansible.builtin.service:
    name: systemd-journald
    state: restarted