---
- name: Include install vars
  include_vars: ../vars/install.yml
  
- name: Git checkout deployment repository
  become: true
  become_user: woody
  ansible.builtin.git:
    repo: git@github.com:solero/solero-server-deployment.git
    dest: /home/woody/solero-server-deployment

- name: Copy secrets
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /home/woody/solero-server-deployment/.secrets/
    owner: woody
    group: woody
    mode: '0600'
  with_fileglob:
    - secrets/*

- name: Get system user info
  ansible.builtin.getent:
    database: passwd
    key: woody

- name: Generate deployment env
  ansible.builtin.template:
    src: ../templates/install.env.j2
    dest: /home/woody/solero-server-deployment/.env
  vars:
    net_mask: "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"
    user: "{{ ansible_facts.getent_passwd['woody'] }}"

- name: Boot woody web services
  ansible.builtin.command:
    cmd: docker compose --ansi never --progress plain --file docker-compose.yml up --detach
    chdir: /home/woody/solero-server-deployment
  register: temp_compose_up
  changed_when: "'Started' in temp_compose_up.stdout"