---
- name: Install NFS
  ansible.builtin.apt:
    name: nfs-common
    state: present

- name: Mount workspaces share
  ansible.posix.mount:
    src: lenny.benpearce.io:/mnt/pool/workspaces
    path: /mnt/workspaces
    fstype: nfs4
    opts: defaults,nofail,x-systemd.after=network-online.target,_netdev
    state: mounted
