- name: Configure jessie
  hosts: jessie
  become: true
  roles:
    - common
    - common_journald
    - common_docker
    - common_users
    - barbie_restore
    - jessie
    - common_docker_compose
