- name: Configure jessie
  hosts: jessie
  become: true
  roles:
    - common
    - common_journald
    - common_users
    - common_users_abilities
    - common_restore
    - common_docker_compose
    - common_docker
    - common_docker_compose_start
