- name: Configure rc
  hosts: rc
  become: true
  roles:
    - common
    - common_journald
    - common_users
    - common_users_abilities
    - common_restore
    - common_docker_compose
    - common_docker
    - rc
    - common_docker_compose_start
