- name: Configure sid
  hosts: sid
  become: true
  roles:
    - common
    - common_journald
    - common_users
    - common_users_abilities
    - common_docker_compose
    - common_docker_config
    - common_docker
    - common_docker_compose_start
