- name: Configure sparks
  hosts: sparks
  become: true
  roles:
    - common
    - common_journald
    - common_docker
    - common_users
    - barbie_restore
    - sparks
    - common_docker_compose
