---
- name: Configure sparks
  hosts: sparks
  become: yes
  roles:
    - common
    - common/docker
    - community.zabbix.zabbix_agent
    - sparks/mounts
    - barbie/restore
    - sparks
    - common/docker/compose
