- name: Configure woody
  hosts: woody
  become: true
  roles:
    - common
    - common_journald
    - common_users
    - common_users_abilities
    - common_restore
    - common_docker_compose
    - common_docker_config
    - common_docker
    - woody
    - common_docker_compose_start
