---
- name: Install libguestfs
  ansible.builtin.apt:
    name:
      - libguestfs-tools
    update_cache: true
    install_recommends: false
    state: latest

- name: Create cloud-init directory
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: 'go+rwx'
    owner: nobody
    group: users
    recurse: true
  with_items: '{{ cloud_init_dir }}'

- name: Download cloud-init image
  register: image
  ansible.builtin.get_url:
    url: '{{ item.url }}'
    dest: '{{ item.image }}'
    mode: '0644'
    force: true
  with_items: '{{ cloud_init_images }}'

- name: Create cloud-init templates
  ansible.builtin.shell: |
    qm unlock {{ item.id }} || true
    qm destroy {{ item.id }} || true
    qm create {{ item.id }} \
      --name {{ item.name }} \
      --tags {{ item.tags }} \
      --memory {{ item.memory | default('2048') }} \
      --cores {{ item.memory | default('2') }} \
      --net0 virtio,bridge=vmbr0 \
      --scsihw virtio-scsi-pci \
      --efidisk0 {{ cloud_init_storage | default('local-lvm') }}:0 \
      --ciuser {{ cloud_init_user }} \
      --sshkeys {{ ansible_env.HOME }}/.ssh/authorized_keys \
      --bios {{ item.bios | default('ovmf') }} \
      --ipconfig0 ip=dhcp \
      --agent 1
    virt-customize -a {{ item.image }} --install qemu-guest-agent
    qm set {{ item.id }} \
      --scsi0 {{ cloud_init_storage | default('local-lvm') }}:0,import-from={{ item.image }},backup=0 \
      --scsi1 {{ cloud_init_storage | default('local-lvm') }}:cloudinit \
      --boot order=scsi0
    qm template {{ item.id }}
  with_items: '{{ cloud_init_images }}'

- name: Remove downloaded cloud-init image
  ansible.builtin.file:
    path: '{{ item.image }}'
    state: absent
  with_items: '{{ cloud_init_images }}'