---
- name: Create LXC templates
  ansible.builtin.shell: |
    pveam download {{ lxc_storage | default('local') }} {{ item.template }}
    pct unlock {{ item.id }} || true
    pct destroy {{ item.id }} || true
    pct create {{ item.id }} \
      /var/lib/vz/template/cache/{{ item.template }} \
      --hostname {{ item.name }} \
      --tags {{ item.tags }} \
      --memory {{ item.memory | default('1024') }} \
      --net0 name=eth0,bridge=vmbr0 \
      --storage {{ cloud_init_storage | default('local-lvm') }} \
      --rootfs {{ cloud_init_storage | default('local-lvm') }}:{{ item.size | default('8') }} \
      --unprivileged 0 \
      --ssh-public-keys {{ ansible_env.HOME }}/.ssh/authorized_keys \
      {% if 'features' in item %}--features {{ item.features }} {% endif %} \
      --ostype ubuntu
    pct template {{ item.id }}
    echo "{{ item.options }}" >> /etc/pve/lxc/{{ item.id }}.conf
  with_items: '{{ lxc_images }}'