---
- name: Include encrypted rclone passphrases
  include_vars: ../vars/rclone_keys.yml

- name: Install rclone
  ansible.builtin.shell: |
    curl https://rclone.org/install.sh | bash
  args:
    executable: /bin/bash
  register: rclone
  changed_when: rclone.rc == 0
  failed_when: rclone.rc not in [0,3]

- name: Install rclone systemd mount
  ansible.builtin.file:
    src: /usr/bin/rclone
    dest: /sbin/mount.rclone
    state: link

- name: Create rclone config directory
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.config/rclone/'
    state: directory

- name: Copy rclone remote service accounts
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ ansible_env.HOME }}/.config/rclone/'
  with_fileglob: '../files/rclone/*.json'

- name : Find rclone repositories
  ansible.builtin.find:
    paths: '{{ ansible_env.HOME }}/.config/rclone/'
    patterns: '*.json'
  register: repos

- name: Generate rclone config
  ansible.builtin.template:
    src: ../templates/rclone.conf.j2
    dest: '{{ ansible_env.HOME }}/.config/rclone/rclone.conf'
  vars:
    config: '{{ ansible_env.HOME }}/.config/rclone'
    drives: '{{ repos.matched }}'