---
- name: Include borg configs
  include_vars: ../vars/borg.yml

- name: Install packages
  ansible.builtin.apt:
    pkg:
      - borgbackup
      - pipx
      - sshfs
    state: present

- name: Install borgmatic
  become: true
  community.general.pipx:
    name: borgmatic  

- name: Create backup repo directories
  ansible.builtin.file:
    path: '/mnt/repo/{{ item.key }}'
    state: directory
  with_items: "{{ borg_configs | dict2items }}"

- name: Initialize borg repositories
  become: true
  shell: borg init --encryption repokey-blake2 /mnt/repo/{{ item.key }}
  environment:
    BORG_PASSPHRASE: "{{ item.value.encryption_passphrase }}"
  register: init
  failed_when: init.rc not in [0,2]
  with_items: "{{ borg_configs | dict2items }}"

- name: Create borgmatic config location
  ansible.builtin.file:
    path: /etc/borgmatic.d
    state: directory
    mode: '0600'

- name: Generate borgmatic configs
  ansible.builtin.template:
    src: ../templates/borgmatic.d.yaml.j2
    dest: '/etc/borgmatic.d/{{ item.key }}.yaml'
  with_items: "{{ borg_configs | dict2items }}"

- name: Copy borgmatic systemd unit
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /lib/systemd/system/
    owner: root
    group: root
    mode: '0644'
  with_fileglob:
    - files/systemd/borgmatic/*

- name: Enable borgmatic timer unit
  ansible.builtin.systemd_service:
    name: borgmatic.timer
    state: started
    enabled: true
    daemon_reload: true
