- name: 🆙 Update & Upgrade Packages
  tags: [update, packages]
  ansible.builtin.apt:
    update_cache: true
    upgrade: "{{ common_update_upgrade | default(true) }}"

- name: 🔍 Check Reboot Flag
  tags: [reboot, check]
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: common_update_reboot_required

- name: 🔄 Reboot If Needed
  tags: [reboot]
  ansible.builtin.reboot:
  when:
    - common_update_reboot | default(true) | bool
    - common_update_reboot_required.stat.exists
