---
- name: Install curl and gnupg
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - gnupg

- name: Add Jellyfin GPG key
  ansible.builtin.get_url:
    url: https://repo.jellyfin.org/ubuntu/jellyfin_team.gpg.key
    dest: /etc/apt/keyrings/jellyfin_team.asc
    mode: '0644'
    force: true

- name: Add Jellyfin repository
  ansible.builtin.apt_repository:
    filename: jellyfin
    repo: 'deb [signed-by=/etc/apt/keyrings/jellyfin_team.asc] https://repo.jellyfin.org/ubuntu {{ ansible_distribution_release | lower }} main'
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install jellyfin-ffmpeg5
  ansible.builtin.apt:
    name: jellyfin-ffmpeg5
    state: present