- name: Copy docker daemon configuration
  ansible.builtin.copy:
    src: files/docker/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0600'

- name: Create docker systemd overrides directory
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'

- name: Copy docker daemon systemd overrides
  ansible.builtin.copy:
    src: files/systemd/docker.service.d/override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf
    owner: root
    group: root
    mode: '0644'

- name: Restart docker service
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Configure journald
  community.general.ini_file:
    path: /etc/systemd/journald.conf
    section: Journal
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - option: Storage
      value: persistent
    - option: Compress
      value: 'yes'
    - option: SystemMaxUse
      value: 50M
    - option: SystemMaxFileSize
      value: 5M
    - option: ForwardToSyslog
      value: 'no'

- name: Restart systemd-journald service
  ansible.builtin.service:
    name: systemd-journald
    state: restarted