---
- name: Include install vars
  include_vars: ../vars/install.yml

- name: Git checkout deployment repository
  become: true
  become_user: sparks
  ansible.builtin.git:
    repo: git@github.com:ben-pearce/dev-server-deployment.git
    dest: /home/sparks/dev-server-deployment

- name: Copy secrets
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /home/sparks/dev-server-deployment/.secrets/
    owner: sparks
    group: sparks
    mode: '0600'
  with_fileglob:
    - secrets/*

- name: Get system user info
  ansible.builtin.getent:
    database: passwd
    key: sparks

- name: Generate deployment env
  ansible.builtin.template:
    src: ../templates/install.env.j2
    dest: /home/sparks/dev-server-deployment/.env
  vars:
    net_mask: "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"
    user: "{{ ansible_facts.getent_passwd['sparks'] }}"