---
- name: Include install vars
  include_vars: ../vars/install.yml

- name: Git checkout deployment repository
  become: true
  become_user: sparks
  ansible.builtin.git:
    repo: git@github.com:ben-pearce/dev-server-deployment.git
    dest: /home/sparks/dev-server-deployment

- name: Copy secrets
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /home/sparks/dev-server-deployment/.secrets/
    owner: sparks
    group: sparks
    mode: '0600'
  with_fileglob:
    - secrets/*

- name: Get system user info
  ansible.builtin.getent:
    database: passwd
    key: "{{ ansible_user }}"

- name: Generate deployment env
  ansible.builtin.template:
    src: ../templates/install.env.j2
    dest: /home/sparks/dev-server-deployment/.env
  vars:
    user: "{{ ansible_facts.getent_passwd[ansible_user] }}"

- name: Boot services
  ansible.builtin.command:
    cmd: docker compose --ansi never --progress plain --file docker-compose.yml up --detach
    chdir: /home/sparks/dev-server-deployment
  register: temp_compose_up
  changed_when: "'Started' in temp_compose_up.stdout"
