---
- name: Install packages
  ansible.builtin.apt:
    pkg:
      - curl
      - gnupg
      - rsync
    state: present

- name: Add azlux GPG key
  ansible.builtin.get_url:
    url: https://azlux.fr/repo.gpg
    dest: /usr/share/keyrings/azlux-archive-keyring.gpg
    mode: '0644'
    force: true

- name: Add azlux repository
  ansible.builtin.apt_repository:
    filename: azlux
    repo: 'deb [signed-by=/usr/share/keyrings/azlux-archive-keyring.gpg] http://packages.azlux.fr/debian/ bookworm main'
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install log2ram
  ansible.builtin.apt:
    name: log2ram
    state: present

- name: Generate log2ram config
  ansible.builtin.template:
    src: ../templates/log2ram.conf.j2
    dest: /etc/log2ram.conf

- name: Restart log2ram service
  ansible.builtin.service:
    name: log2ram
    state: restarted
