---
- name: Install NFS
  ansible.builtin.apt:
    name: nfs-common
    state: present

- name: Mount media share
  ansible.posix.mount:
    src: lenny.benpearce.io:/mnt/pool/media
    path: /mnt/media
    fstype: nfs4
    opts: defaults,nofail,x-systemd.after=network-online.target,_netdev
    state: mounted

- name: Mount music share
  ansible.posix.mount:
    src: lenny.benpearce.io:/mnt/fast/music
    path: /mnt/music
    fstype: nfs4
    opts: defaults,nofail,x-systemd.after=network-online.target,_netdev
    state: mounted

- name: Mount cloud share
  ansible.posix.mount:
    src: lenny.benpearce.io:/mnt/fast/cloud
    path: /mnt/cloud
    fstype: nfs4
    opts: defaults,nofail,x-systemd.after=network-online.target,_netdev
    state: mounted
