
certbot_cloudflare_acme_test: "https://acme-staging-v02.api.letsencrypt.org/directory"
certbot_cloudflare_acme_live: "https://acme-v02.api.letsencrypt.org/directory"

certbot_cloudflare_acme_server: "{{ certbot_cloudflare_acme_test }}"