---
- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - python3-docker
    state: latest
    update_cache: true

- name: Add Docker Repository
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: "https://download.docker.com/linux/ubuntu"
    suites: '{{ ansible_distribution_release }}'
    components: [stable]
    signed_by: https://download.docker.com/linux/ubuntu/gpg
    state: present
    enabled: true

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: Add the user to Docker group
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    group: docker