---
- name: Copy docker daemon configuration
  ansible.builtin.copy:
    src: files/docker/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0600'

- name: Create docker systemd overrides directory
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'

- name: Copy docker daemon systemd overrides
  ansible.builtin.copy:
    src: files/systemd/docker.service.d/override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf
    owner: root
    group: root
    mode: '0644'

- name: Restart docker service
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Add 'jellyfin-ffmpeg' alias 
  ansible.builtin.lineinfile:
    dest: /etc/cloud/templates/hosts.debian.tmpl
    line: "{{ hostvars['jellyfin_ffmpeg'].ansible_host }} jellyfin-ffmpeg"
    state: present

- name: Add 'paperless-scan' alias 
  ansible.builtin.lineinfile:
    dest: /etc/cloud/templates/hosts.debian.tmpl
    line: "{{ printer_addr }} paperless-scan"
    state: present

- name: Mount hardlinks
  ansible.posix.mount:
    src: '{{ item.src }}'
    path: '{{ item.path }}'
    fstype: none
    opts: x-systemd.requires={{ item.requires }},x-systemd.after={{ item.requires }},bind
    state: mounted
  with_items:
    - src: /mnt/cloud
      path: /opt/home-server-deployment/data/nextcloud/data/ben/files
      requires: /mnt/cloud
    - src: /mnt/cloud/Photos
      path: /opt/home-server-deployment/data/immich/upload
      requires: /mnt/cloud
    - src: /mnt/cloud/Paperless
      path: /opt/home-server-deployment/data/paperless/media/documents/originals
      requires: /mnt/cloud

- name: Configure journald
  community.general.ini_file:
    path: /etc/systemd/journald.conf
    section: Journal
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - option: Storage
      value: volatile
    - option: Compress
      value: 'yes'
    - option: SystemMaxUse
      value: 50M
    - option: SystemMaxFileSize
      value: 5M
    - option: ForwardToSyslog
      value: 'no'

- name: Restart systemd-journald service
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
