#!/bin/bash
set -euo pipefail

mode="$1"

containers=$(docker \
    container ls \
    --filter name=gitlab \
    --format "{{.Names}}"
)

backup_dir="/mnt/data/applications/gitlab/backups"

if [[ -z "$mode" ]]; then
    echo "Usage: $0 <create|clean>"
    exit 1
fi

case "$mode" in
    create)
        for container in $containers; do
            /usr/bin/docker compose \
                --project-directory "$COMPOSE_REPOSITORY" \
                exec "$container" \
                gitlab-backup create
        done
        ;;
    clean)
        if [[ -d "$backup_dir" ]]; then
            rm -rf "${backup_dir:?}/"*
        else
            echo "Backup directory does not exist: $backup_dir"
            exit 1
        fi
        ;;
    *)
        echo "Unknown mode: $mode"
        exit 1
        ;;
esac