common_users_ssh_config:
  - user: root
    remote_user: borg
    hostname: jessie.benpearce.io
    host: jessie
    strict_host_key_checking: 'no'
    identity_file: /root/.ssh/id_ed25519
  - user: root
    remote_user: borg
    hostname: etch.benpearce.io
    host: etch
    strict_host_key_checking: 'no'
    identity_file: /root/.ssh/id_ed25519
  - user: root
    remote_user: borg
    hostname: rc.benpearce.io
    host: rc
    strict_host_key_checking: 'no'
    identity_file: /root/.ssh/id_ed25519
  - user: root
    remote_user: borg
    hostname: sparks.benpearce.io
    host: sparks
    strict_host_key_checking: 'no'
    identity_file: /root/.ssh/id_ed25519
  - user: root
    remote_user: borg
    hostname: woody.benpearce.io
    host: woody
    strict_host_key_checking: 'no'
    identity_file: /root/.ssh/id_ed25519
  - user: root
    remote_user: borg
    hostname: zurg.benpearce.io
    host: zurg
    strict_host_key_checking: 'no'
    identity_file: /root/.ssh/id_ed25519
