---
- name: Add barbie to known hosts
  known_hosts:
    name: "{{ hostvars['barbie'].ansible_host }}"
    state: present
    key: "{{ lookup('pipe', 'ssh-keyscan ' + hostvars['barbie'].ansible_host) }}"

- name: Create restore points  
  ansible.builtin.file:
    path: '{{ item }}'
    owner: '{{ inventory_hostname }}'
    group: '{{ inventory_hostname }}'
    state: directory
  register: borg_restore_point
  failed_when: borg_restore_point.state != 'directory'
  with_items: '{{ borg_source_directories }}'
  
- name: Add barbie to ssh config
  community.general.ssh_config:
    user: root
    remote_user: '{{ inventory_hostname }}'
    hostname: "{{ hostvars['barbie'].ansible_host }}"
    host: barbie
    identity_file: /root/.ssh/id_ed25519
    state: present

- name: Enable borgmatic timer unit
  ansible.builtin.systemd:
    name: borgmatic.timer
    state: started
    enabled: true