---
- name: Check mailcow directory
  ansible.builtin.find:
    paths: /mnt/data/mailcow-dockerized
    file_type: any
  register: mailcow_install_directory

- name: Move mailcow directory
  ansible.builtin.command: mv /mnt/data/mailcow-dockerized /mnt/data/mailcow-dockerized.bak
  args:
    removes: /mnt/data/mailcow-dockerized
    creates: /mnt/data/mailcow-dockerized.bak
  when: mailcow_install_directory.matched >= 1

- name: Git checkout mailcow repository
  ansible.builtin.git:
    repo: https://github.com/mailcow/mailcow-dockerized
    dest: /mnt/data/mailcow-dockerized

- name: Delete fresh mailcow data
  ansible.builtin.file:
    path: /mnt/data/mailcow-dockerized/data
    state: absent
  when: mailcow_install_directory.matched >= 1

- name: Move mailcow backups and configuration
  ansible.builtin.shell: |
    mv /mnt/data/mailcow-dockerized.bak/backups /mnt/data/mailcow-dockerized;
    mv /mnt/data/mailcow-dockerized.bak/data /mnt/data/mailcow-dockerized;
    mv /mnt/data/mailcow-dockerized.bak/mailcow.conf /mnt/data/mailcow-dockerized
  when: mailcow_install_directory.matched >= 1

- name: Delete mailcow temp directory
  ansible.builtin.file:
    path: /mnt/data/mailcow-dockerized.bak
    state: absent
  when: mailcow_install_directory.matched >= 1

- name: Boot mailcow services
  community.docker.docker_compose_v2:
    project_src: /mnt/data/mailcow-dockerized
  with_items: '{{ common_docker_compose }}'
